kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:namespace-manager
subjects:
- kind: ServiceAccount
  name: splunk-operator
roleRef:
  kind: Role
  name: splunk:operator:namespace-manager
  apiGroup: rbac.authorization.k8s.io
