alertmanager:
  service:
    type: LoadBalancer
prometheusOperator:
  service:
    type: LoadBalancer
prometheus:
  service:
    type: LoadBalancer
  thanosService:
    service:
      type: LoadBalancer
grafana:
  service:
    type: LoadBalancer
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder:
          type: file
          disableDeletion: true
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: jvm-application-grafana-94mf8hkh4h
